/// Farmer Model
/// 
/// This represents a farmer's complete profile information.
/// Used for registration and displaying farmer details.
class FarmerModel {
  // ==========================================================================
  // Basic Information
  // ==========================================================================
  
  /// Unique farmer number (e.g., "F-2025-0001") - Generated by backend
  final String? farmerNo;
  
  /// First name (Required)
  final String firstName;
  
  /// Middle name (Optional)
  final String? middleName;
  
  /// Surname/Last name (Required)
  final String surname;
  
  /// Date of birth in format: YYYY-MM-DD (Optional)
  final String? dateOfBirth;
  
  /// Gender: "male" or "female" (Required)
  final String gender;
  
  // ==========================================================================
  // Contact Information
  // ==========================================================================
  
  /// Primary phone number (Required)
  final String phone1;
  
  /// Secondary phone number (Optional)
  final String? phone2;
  
  /// Email address (Optional)
  final String? email;
  
  /// Physical address/description (Optional)
  final String? physicalAddress;
  
  // ==========================================================================
  // Identity Information
  // ==========================================================================
  
  /// Identity card type ID (1=NIDA, 2=VOTERS ID, 3=LICENCE, etc.)
  final int? identityCardTypeId;
  
  /// Identity card number (Optional)
  final String? identityNumber;
  
  /// School/Education level ID (Optional)
  final int? schoolLevelId;
  
  // ==========================================================================
  // Location Information (Hierarchical)
  // ==========================================================================
  
  /// Country ID (Optional)
  final int? countryId;
  
  /// Region ID (Optional)
  final int? regionId;
  
  /// District ID (Optional)
  final int? districtId;
  
  /// Ward ID (Optional)
  final int? wardId;
  
  /// Village ID (Optional)
  final int? villageId;
  
  /// Street ID (Optional)
  final int? streetId;
  
  // ==========================================================================
  // Farmer-Specific Information
  // ==========================================================================
  
  /// Type of farmer: "Individual" or "Organization"
  final String? farmerType;
  
  /// Name of farmer organization membership (Optional)
  final String? farmerOrganizationMembership;
  
  // ==========================================================================
  // System Information
  // ==========================================================================
  
  /// Who created this record (User ID)
  final int? createdBy;
  
  /// Status: "active" or "inactive"
  final String? status;
  
  /// When this record was created
  final DateTime? createdAt;
  
  /// When this record was last updated
  final DateTime? updatedAt;

  // ==========================================================================
  // Constructor
  // ==========================================================================
  
  FarmerModel({
    this.farmerNo,
    required this.firstName,
    this.middleName,
    required this.surname,
    required this.phone1,
    this.phone2,
    this.email,
    this.physicalAddress,
    this.farmerOrganizationMembership,
    this.dateOfBirth,
    required this.gender,
    this.identityCardTypeId,
    this.identityNumber,
    this.streetId,
    this.schoolLevelId,
    this.villageId,
    this.wardId,
    this.districtId,
    this.regionId,
    this.countryId,
    this.farmerType,
    this.createdBy,
    this.status,
    this.createdAt,
    this.updatedAt,
  });

  // ==========================================================================
  // Convert from JSON (API Response) to FarmerModel
  // ==========================================================================
  
  /// Creates a FarmerModel from JSON data received from the backend API.
  /// 
  /// Example:
  /// ```dart
  /// final json = {
  ///   'firstName': 'John',
  ///   'surname': 'Doe',
  ///   'phone1': '+255712345678',
  ///   'gender': 'male'
  /// };
  /// final farmer = FarmerModel.fromJson(json);
  /// ```
  factory FarmerModel.fromJson(Map<String, dynamic> json) {
    return FarmerModel(
      farmerNo: json['farmerNo'] as String?,
      firstName: json['firstName'] as String,
      middleName: json['middleName'] as String?,
      surname: json['surname'] as String,
      phone1: json['phone1'] as String,
      phone2: json['phone2'] as String?,
      email: json['email'] as String?,
      physicalAddress: json['physicalAddress'] as String?,
      farmerOrganizationMembership: json['farmerOrganizationMembership'] as String?,
      dateOfBirth: json['dateOfBirth'] as String?,
      gender: json['gender'] as String,
      identityCardTypeId: json['identityCardTypeId'] as int?,
      identityNumber: json['identityNumber'] as String?,
      streetId: json['streetId'] as int?,
      schoolLevelId: json['schoolLevelId'] as int?,
      villageId: json['villageId'] as int?,
      wardId: json['wardId'] as int?,
      districtId: json['districtId'] as int?,
      regionId: json['regionId'] as int?,
      countryId: json['countryId'] as int?,
      farmerType: json['farmerType'] as String?,
      createdBy: json['createdBy'] as int?,
      status: json['status'] as String?,
      createdAt: json['created_at'] != null 
          ? DateTime.parse(json['created_at'] as String)
          : null,
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : null,
    );
  }

  // ==========================================================================
  // Convert from FarmerModel to JSON (for API Request)
  // ==========================================================================
  
  /// Converts this FarmerModel to JSON format to send to the backend API.
  /// Only includes non-null values.
  /// 
  /// Example:
  /// ```dart
  /// final farmer = FarmerModel(...);
  /// final json = farmer.toJson();
  /// // Send json to API
  /// ```
  Map<String, dynamic> toJson() {
    return {
      'firstName': firstName,
      if (middleName != null) 'middleName': middleName,
      'surname': surname,
      'phone1': phone1,
      if (phone2 != null) 'phone2': phone2,
      if (email != null) 'email': email,
      if (physicalAddress != null) 'physicalAddress': physicalAddress,
      if (farmerOrganizationMembership != null) 
        'farmerOrganizationMembership': farmerOrganizationMembership,
      if (dateOfBirth != null) 'dateOfBirth': dateOfBirth,
      'gender': gender,
      if (identityCardTypeId != null) 'identityCardTypeId': identityCardTypeId,
      if (identityNumber != null) 'identityNumber': identityNumber,
      if (streetId != null) 'streetId': streetId,
      if (schoolLevelId != null) 'schoolLevelId': schoolLevelId,
      if (villageId != null) 'villageId': villageId,
      if (wardId != null) 'wardId': wardId,
      if (districtId != null) 'districtId': districtId,
      if (regionId != null) 'regionId': regionId,
      if (countryId != null) 'countryId': countryId,
      if (farmerType != null) 'farmerType': farmerType,
      if (createdBy != null) 'createdBy': createdBy,
      if (status != null) 'status': status,
      if (createdAt != null) 'created_at': createdAt!.toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt!.toIso8601String(),
    };
  }

  // ==========================================================================
  // Useful Helper Methods
  // ==========================================================================
  
  /// Returns the full name by combining first name, middle name, and surname.
  /// 
  /// Example: "John Doe Smith"
  String get fullName {
    final parts = <String>[
      firstName,
      if (middleName != null && middleName!.isNotEmpty) middleName!,
      surname,
    ];
    return parts.join(' ');
  }

  /// Checks if the farmer has provided complete location information.
  /// Returns true if country, region, district, and ward are all filled.
  bool get hasCompleteLocation {
    return countryId != null &&
        regionId != null &&
        districtId != null &&
        wardId != null;
  }

  /// Checks if the farmer has provided identity card information.
  /// Returns true if both identity card type and number are filled.
  bool get hasIdentityInfo {
    return identityCardTypeId != null && 
        identityNumber != null && 
        identityNumber!.isNotEmpty;
  }

  // ==========================================================================
  // Display/Debug Method
  // ==========================================================================
  
  /// Returns a readable string representation of this farmer.
  /// Useful for debugging and logging.
  @override
  String toString() {
    return 'FarmerModel('
        'farmerNo: $farmerNo, '
        'name: $fullName, '
        'phone: $phone1, '
        'email: $email, '
        'gender: $gender'
        ')';
  }
}
